####################################################################
# Visual Servoing Docker Container                                    #
#                                                                    #
# This code is available under the MIT license and comes without     #
# any explicit or implicit warranty.                                 #
#                                                                    #
# (C) Alessandro Scherl 2024 <alessandro.scherl@technikum-wien.at>  #
####################################################################

# Base image
FROM ubuntu:20.04

# Metadata
MAINTAINER Alessandro Scherl (alessandro.scherl@technikum-wien.at)

# Environment setup
ENV DEBIAN_FRONTEND=noninteractive
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8

# Install base dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    python3-dev \
    gnupg2 \
    git \
    nano \
    gedit \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install X11 and virtual display dependencies
RUN apt-get update && apt-get install -y \
    xvfb \
    x11vnc \
    x11-utils \
    x11-xserver-utils \
    mesa-utils \
    libgl1-mesa-glx \
    libgl1-mesa-dri \
    libglu1-mesa \
    libxrender1 \
    libxi6 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip and install Python requirements
RUN pip3 install --upgrade pip
COPY requirements/requirements.txt .
RUN pip install -r requirements.txt

# Install ROS Noetic
RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu focal main" > /etc/apt/sources.list.d/ros-latest.list' && \
    curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add - && \
    apt-get update && \
    apt-get install -y \
        ros-noetic-desktop-full \
        ros-noetic-realsense2-camera \
        ros-noetic-moveit \
        ros-noetic-realsense2-description \
        ros-noetic-rgbd-launch \
        ros-noetic-gazebo-ros-pkgs \
        ros-noetic-gazebo-ros-control \
        python3-rosdep \
        python3-rosinstall \
        python3-rosinstall-generator \
        python3-wstool \
        build-essential \
    && rm -rf /var/lib/apt/lists/*

# ROS workspace setup
RUN echo "source /opt/ros/noetic/setup.bash" >> ~/.bashrc && \
    echo "export DISABLE_ROS1_EOL_WARNINGS=1" >> ~/.bashrc && \
    mkdir -p ~/catkin_ws/src && \
    /bin/bash -c "source /opt/ros/noetic/setup.bash && cd ~/catkin_ws && catkin_make"

# Initialize rosdep
RUN rosdep init && \
    rosdep update

# Set up catkin workspace
WORKDIR /root/catkin_ws
ENV ROS_DISTRO=noetic
RUN /bin/bash -c '. /opt/ros/noetic/setup.bash; cd /root/catkin_ws; catkin_make' && \
    echo "source /root/catkin_ws/devel/setup.bash" >> ~/.bashrc

# Install additional dependencies
RUN pip install git+https://github.com/lucasb-eyer/pydensecrf.git

# Create startup script for Xvfb
RUN echo '#!/bin/bash\n\
if [ ! -z "$VIRTUAL_DISPLAY" ]; then\n\
    Xvfb :99 -screen 0 1920x1080x24 -nolisten tcp -nolisten unix &\n\
    export DISPLAY=:99\n\
fi\n\
exec "$@"' > /entrypoint.sh && \
    chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
